name: Create Production Builds & OTA Updates

on:
  push:
    branches:
      - master
      - main

jobs:
  publish_update:
    type: update
    params:
      branch: production
      message: Auto update from GitHub push

  build_android:
    type: build
    params:
      platform: android
      profile: production

